name: ci workflow for php  projects
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
permissions:
  contents: read
jobs:
  php_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, zip
        
    
    - name: Run PHP Linter
      run: |
        echo "Running PHP syntax check..."
        find . -type f -name "*.php" -print0 | xargs -0 -n1 php -l


    - name: security check
      run: composer audit

    - name: Notify  if builds
      if: failure()
      run: echo "‚ùå Build failed!" 
  security:
    runs-on: windows-latest
    needs: [php_build]
    steps:
      - uses: actions/checkout@v4

      # üß† Run Trivy to scan the file system and dependencies
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'          # Scans file system
          ignore-unfixed: true     # Skip vulnerabilities without a fix
          format: 'table'          # or 'sarif' for GitHub Security tab
          output: 'trivy-results.txt'
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.txt

  deploy:
    needs: php_build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setting up php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, zip

    - name: Start php server
      run: php -S localhost:8000 main.php
      shell: pwsh
    
    - name: Notify  if builds
      if: failure()
      run: echo "‚ùå Deploy failed!"

  notify:
    runs-on: windows-latest
    needs: [php_build, deploy]
    steps:
      - name: Notify on Success
        run: echo "‚úÖ Deployment successful!"
  cache:
    runs-on: windows-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
  
  


